### PR TITLE
Libbpf sync 2023 02 16 t22 23 13.708 z

### PR DESCRIPTION
**Pull request by liu-song-6**
```
Dumping existing libbpf commit signatures...
WORKDIR:          /home/songliubraving/local/libbpf
LINUX REPO:       /home/songliubraving/local/kernel/linux-git/
LIBBPF REPO:      ../libbpf
TEMP DIR:         /tmp/tmp.nN6WLprpLj
SUFFIX:           2023-02-16T22-23-13.708Z
BASE COMMIT:      'a5f6b9d577eb ("Merge branch 'Enable struct_ops programs to be sleepable'")'
TIP COMMIT:       '6c20822fada1 ("bpf, test_run: fix &xdp_frame misplacement for LIVE_FRAMES")'
BPF BASE COMMIT:  'e8c8fd9b8393 ("Merge branch 'bpf, sockmap: Fix infinite recursion in sock_map_close'")'
BPF TIP COMMIT:   '6c20822fada1 ("bpf, test_run: fix &xdp_frame misplacement for LIVE_FRAMES")'
SQUASH COMMIT:    a69ae1df3223ddb58d58a4f3ba16e39682a8bc9a
BASELINE TAG:     libbpf-baseline-2023-02-16T22-23-13.708Z
TIP TAG:          libbpf-tip-2023-02-16T22-23-13.708Z
BPF BASELINE TAG: libbpf-bpf-baseline-2023-02-16T22-23-13.708Z
BPF TIP TAG:      libbpf-bpf-tip-2023-02-16T22-23-13.708Z
SQUASH BASE TAG:  libbpf-squash-base-2023-02-16T22-23-13.708Z
SQUASH TIP TAG:   libbpf-squash-tip-2023-02-16T22-23-13.708Z
VIEW TAG:         libbpf-view-2023-02-16T22-23-13.708Z
LIBBPF SYNC TAG:  libbpf-sync-2023-02-16T22-23-13.708Z
PATCHES:          /tmp/tmp.nN6WLprpLj/patches
Switched to a new branch 'libbpf-squash-tip-2023-02-16T22-23-13.708Z'
Picking '139df64d26fd ("libbpf: Fix malformed documentation formatting")'...
Picking 'e4ce876f10a2 ("libbpf: Add documentation to map pinning API functions")'...
Picking '1d3cab43f4c7 ("Documentation: bpf: correct spelling")'...
Picking 'e85465e420be ("libbpf: Simplify barrier_var()")'...
Picking '25c76ed42821 ("libbpf: Fix unbounded memory access in bpf_usdt_arg()")'...
Picking '42fae973c2b1 ("libbpf: Fix BPF_PROBE_READ{_STR}_INTO() on s390x")'...
Picking 'e2bd9742989b ("tools/bpf: Use tab instead of white spaces to sync bpf.h")'...
Picking '8f1669319c31 ("libbpf: add the capability to specify netlink proto in libbpf_netlink_send_recv")'...
Picking '04d58f1b26a4 ("libbpf: add API to get XDP/XSK supported features")'...
Picking '17c9b4e1a7d1 ("bpf: fix typo in header for bpf_perf_prog_read_value")'...
Picking 'd1d7730ff875 ("libbpf: Correctly set the kernel code version in Debian kernel.")'...
Picking '02fc0e73e852 ("libbpf: Always use libbpf_err to return an error in bpf_xdp_query()")'...
Picking 'ab8684b8cecf ("libbpf: Add sample_period to creation options")'...
Picking '17bcd27a08a2 ("libbpf: Fix alen calculation in libbpf_nla_dump_errormsg()")'...
Picking '9c395c1b99bd ("bpf: Add basic bpf_rb_{root,node} support")'...
Warning! Cherry-picking '9c395c1b99bd ("bpf: Add basic bpf_rb_{root,node} support") failed, checking if it's non-libbpf files causing problems...
Looks like only non-libbpf files have conflicts, ignoring...
warning: adding embedded git repository: buck-out/gen/baseline-sources/baseline-sources
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint:   git submodule add <url> buck-out/gen/baseline-sources/baseline-sources
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint:   git rm --cached buck-out/gen/baseline-sources/baseline-sources
hint:
hint: See "git help submodule" for more information.
warning: adding embedded git repository: buck-out/gen/target-sources/target-sources
Success! All cherry-pick conflicts were resolved for '9c395c1b99bd ("bpf: Add basic bpf_rb_{root,node} support")'!
Commit 'c9883ee9d110 ("libbpf: Optimized return value in libbpf_strerror when errno is libbpf errno")' is synced into libbpf as:
- 8d719b0c08c1 ("libbpf: Optimized return value in libbpf_strerror when errno is libbpf errno")
Skipping 'c9883ee9d110 ("libbpf: Optimized return value in libbpf_strerror when errno is libbpf errno")' due to unique match...
Commit '872aec4b5f63 ("libbpf: Fix single-line struct definition output in btf_dump")' is synced into libbpf as:
- db117049443d ("libbpf: Fix single-line struct definition output in btf_dump")
Skipping '872aec4b5f63 ("libbpf: Fix single-line struct definition output in btf_dump")' due to unique match...
Commit '21a9a1bcccaa ("libbpf: Handle non-standardly sized enums better in BTF-to-C dumper")' is synced into libbpf as:
- e6e0e3fd859e ("libbpf: Handle non-standardly sized enums better in BTF-to-C dumper")
Skipping '21a9a1bcccaa ("libbpf: Handle non-standardly sized enums better in BTF-to-C dumper")' due to unique match...
Commit '25a4481b4136 ("libbpf: Fix btf__align_of() by taking into account field offsets")' is synced into libbpf as:
- 58b164237a44 ("libbpf: Fix btf__align_of() by taking into account field offsets")
Skipping '25a4481b4136 ("libbpf: Fix btf__align_of() by taking into account field offsets")' due to unique match...
Commit 'ea2ce1ba99aa ("libbpf: Fix BTF-to-C converter's padding logic")' is synced into libbpf as:
- 0b80970cb65e ("libbpf: Fix BTF-to-C converter's padding logic")
Skipping 'ea2ce1ba99aa ("libbpf: Fix BTF-to-C converter's padding logic")' due to unique match...
Commit '4fb877aaa179 ("libbpf: Fix btf_dump's packed struct determination")' is synced into libbpf as:
- b9f1a06c7042 ("libbpf: Fix btf_dump's packed struct determination")
Skipping '4fb877aaa179 ("libbpf: Fix btf_dump's packed struct determination")' due to unique match...
Commit 'e26aa600ba6a ("bpf: Add flag BPF_F_NO_TUNNEL_KEY to bpf_skb_set_tunnel_key()")' is synced into libbpf as:
- 41ac436073dc ("bpf: Add flag BPF_F_NO_TUNNEL_KEY to bpf_skb_set_tunnel_key()")
Skipping 'e26aa600ba6a ("bpf: Add flag BPF_F_NO_TUNNEL_KEY to bpf_skb_set_tunnel_key()")' due to unique match...
Commit '1520e8466d68 ("libbpf: Fix build warning on ref_ctr_off for 32-bit architectures")' is synced into libbpf as:
- f7dba2c3135f ("libbpf: Fix build warning on ref_ctr_off for 32-bit architectures")
Skipping '1520e8466d68 ("libbpf: Fix build warning on ref_ctr_off for 32-bit architectures")' due to unique match...
Commit 'e6b4e1d759d3 ("libbpf: Show error info about missing ".BTF" section")' is synced into libbpf as:
- 49bd40e8698f ("libbpf: Show error info about missing ".BTF" section")
Skipping 'e6b4e1d759d3 ("libbpf: Show error info about missing ".BTF" section")' due to unique match...
Commit '4ec38eda85b9 ("libbpf: start v1.2 development cycle")' is synced into libbpf as:
- 7d075a739e4e ("libbpf: start v1.2 development cycle")
Skipping '4ec38eda85b9 ("libbpf: start v1.2 development cycle")' due to unique match...
Commit '07453245620c ("libbpf: fix errno is overwritten after being closed.")' is synced into libbpf as:
- 8cd371816bc8 ("libbpf: fix errno is overwritten after being closed.")
Skipping '07453245620c ("libbpf: fix errno is overwritten after being closed.")' due to unique match...
Commit '7244eb669397 ("libbpf: Fix invalid return address register in s390")' is synced into libbpf as:
- 09f1324bd7e5 ("libbpf: Fix invalid return address register in s390")
Skipping '7244eb669397 ("libbpf: Fix invalid return address register in s390")' due to unique match...
Commit '678a1c036199 ("libbpf: Added the description of some API functions")' is synced into libbpf as:
- 34fadd0fbe95 ("libbpf: Added the description of some API functions")
Skipping '678a1c036199 ("libbpf: Added the description of some API functions")' due to unique match...
Commit 'bb5747cfbc4b ("libbpf: Restore errno after pr_warn.")' is synced into libbpf as:
- b92963bbe2df ("libbpf: Restore errno after pr_warn.")
Skipping 'bb5747cfbc4b ("libbpf: Restore errno after pr_warn.")' due to unique match...
Commit '00883922ab40 ("libbpf: Add LoongArch support to bpf_tracing.h")' is synced into libbpf as:
- f758104b07d0 ("libbpf: Add LoongArch support to bpf_tracing.h")
Skipping '00883922ab40 ("libbpf: Add LoongArch support to bpf_tracing.h")' due to unique match...
Commit 'acd3b7768048 ("libbpf: Return -ENODATA for missing btf section")' is synced into libbpf as:
- d572b6359e7b ("libbpf: Return -ENODATA for missing btf section")
Skipping 'acd3b7768048 ("libbpf: Return -ENODATA for missing btf section")' due to unique match...
Commit '6d0c4b11e743 ("libbpf: Poison strlcpy()")' is synced into libbpf as:
- 42d77b062c0e ("libbpf: Poison strlcpy()")
Skipping '6d0c4b11e743 ("libbpf: Poison strlcpy()")' due to unique match...
Commit '6920b08661e3 ("libbpf: Fix map creation flags sanitization")' is synced into libbpf as:
- ce8d078ac762 ("libbpf: Fix map creation flags sanitization")
Skipping '6920b08661e3 ("libbpf: Fix map creation flags sanitization")' due to unique match...
Commit '2fa074536590 ("libbpf: Replace '.' with '_' in legacy kprobe event name")' is synced into libbpf as:
- 49e950dcfacd ("libbpf: Replace '.' with '_' in legacy kprobe event name")
Skipping '2fa074536590 ("libbpf: Replace '.' with '_' in legacy kprobe event name")' due to unique match...
Commit 'd219df60a70e ("bpf: Add ipip6 and ip6ip decap support for bpf_skb_adjust_room()")' is synced into libbpf as:
- ed09f7e65b80 ("bpf: Add ipip6 and ip6ip decap support for bpf_skb_adjust_room()")
Skipping 'd219df60a70e ("bpf: Add ipip6 and ip6ip decap support for bpf_skb_adjust_room()")' due to unique match...
Commit '2b3486bc2d23 ("bpf: Introduce device-bound XDP programs")' is synced into libbpf as:
- 7d68fca99c41 ("bpf: Introduce device-bound XDP programs")
Skipping '2b3486bc2d23 ("bpf: Introduce device-bound XDP programs")' due to unique match...
Commit '3c59623d8294 ("libbpf: Add support for fetching up to 8 arguments in kprobes")' is synced into libbpf as:
- c94a3fd8060d ("libbpf: Add support for fetching up to 8 arguments in kprobes")
Skipping '3c59623d8294 ("libbpf: Add support for fetching up to 8 arguments in kprobes")' due to unique match...
Commit '013290329a07 ("libbpf: Add 6th argument support for x86-64 in bpf_tracing.h")' is synced into libbpf as:
- 4759a83309ac ("libbpf: Add 6th argument support for x86-64 in bpf_tracing.h")
Skipping '013290329a07 ("libbpf: Add 6th argument support for x86-64 in bpf_tracing.h")' due to unique match...
Commit '1dac40ac8742 ("libbpf: Fix arm and arm64 specs in bpf_tracing.h")' is synced into libbpf as:
- 1b48e879a42d ("libbpf: Fix arm and arm64 specs in bpf_tracing.h")
Skipping '1dac40ac8742 ("libbpf: Fix arm and arm64 specs in bpf_tracing.h")' due to unique match...
Commit '1222445a5bf6 ("libbpf: Complete mips spec in bpf_tracing.h")' is synced into libbpf as:
- 31e29d93460f ("libbpf: Complete mips spec in bpf_tracing.h")
Skipping '1222445a5bf6 ("libbpf: Complete mips spec in bpf_tracing.h")' due to unique match...
Commit '2eb2be30b8da ("libbpf: Complete powerpc spec in bpf_tracing.h")' is synced into libbpf as:
- 7b86294a90dd ("libbpf: Complete powerpc spec in bpf_tracing.h")
Skipping '2eb2be30b8da ("libbpf: Complete powerpc spec in bpf_tracing.h")' due to unique match...
Commit '7f60f5d85e29 ("libbpf: Complete sparc spec in bpf_tracing.h")' is synced into libbpf as:
- ffbc84cf6f6a ("libbpf: Complete sparc spec in bpf_tracing.h")
Skipping '7f60f5d85e29 ("libbpf: Complete sparc spec in bpf_tracing.h")' due to unique match...
Commit 'b13ed8ca7fba ("libbpf: Complete riscv arch spec in bpf_tracing.h")' is synced into libbpf as:
- 9db84de5f0b7 ("libbpf: Complete riscv arch spec in bpf_tracing.h")
Skipping 'b13ed8ca7fba ("libbpf: Complete riscv arch spec in bpf_tracing.h")' due to unique match...
Commit '0ac086567916 ("libbpf: Fix and complete ARC spec in bpf_tracing.h")' is synced into libbpf as:
- c978366c38a0 ("libbpf: Fix and complete ARC spec in bpf_tracing.h")
Skipping '0ac086567916 ("libbpf: Fix and complete ARC spec in bpf_tracing.h")' due to unique match...
Commit '55ff00d5393b ("libbpf: Complete LoongArch (loongarch) spec in bpf_tracing.h")' is synced into libbpf as:
- 2094e1b37e5f ("libbpf: Complete LoongArch (loongarch) spec in bpf_tracing.h")
Skipping '55ff00d5393b ("libbpf: Complete LoongArch (loongarch) spec in bpf_tracing.h")' due to unique match...
Commit 'ac4afd6e6fa4 ("libbpf: Add BPF_UPROBE and BPF_URETPROBE macro aliases")' is synced into libbpf as:
- ed8b4c90ea92 ("libbpf: Add BPF_UPROBE and BPF_URETPROBE macro aliases")
Skipping 'ac4afd6e6fa4 ("libbpf: Add BPF_UPROBE and BPF_URETPROBE macro aliases")' due to unique match...
Commit '8ccabeef9133 ("libbpf: Improve syscall tracing support in bpf_tracing.h")' is synced into libbpf as:
- 672401ae0916 ("libbpf: Improve syscall tracing support in bpf_tracing.h")
Skipping '8ccabeef9133 ("libbpf: Improve syscall tracing support in bpf_tracing.h")' due to unique match...
Commit 'd21fbceedd90 ("libbpf: Define x86-64 syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- df16188dc200 ("libbpf: Define x86-64 syscall regs spec in bpf_tracing.h")
Skipping 'd21fbceedd90 ("libbpf: Define x86-64 syscall regs spec in bpf_tracing.h")' due to unique match...
Commit 'ff00f9cbd2dd ("libbpf: Define i386 syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- b2d8a8d269e9 ("libbpf: Define i386 syscall regs spec in bpf_tracing.h")
Skipping 'ff00f9cbd2dd ("libbpf: Define i386 syscall regs spec in bpf_tracing.h")' due to unique match...
Commit 'e82b96a3a99f ("libbpf: Define s390x syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- bd6e1ec31112 ("libbpf: Define s390x syscall regs spec in bpf_tracing.h")
Skipping 'e82b96a3a99f ("libbpf: Define s390x syscall regs spec in bpf_tracing.h")' due to unique match...
Commit '3a95c42d65d5 ("libbpf: Define arm syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- a095b4f04d1e ("libbpf: Define arm syscall regs spec in bpf_tracing.h")
Skipping '3a95c42d65d5 ("libbpf: Define arm syscall regs spec in bpf_tracing.h")' due to unique match...
Commit '3488ea0584bb ("libbpf: Define arm64 syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- 7f627a62021b ("libbpf: Define arm64 syscall regs spec in bpf_tracing.h")
Skipping '3488ea0584bb ("libbpf: Define arm64 syscall regs spec in bpf_tracing.h")' due to unique match...
Commit 'cfd0bbe91536 ("libbpf: Define mips syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- a005bb2ff87c ("libbpf: Define mips syscall regs spec in bpf_tracing.h")
Skipping 'cfd0bbe91536 ("libbpf: Define mips syscall regs spec in bpf_tracing.h")' due to unique match...
Commit 'c1cc01a2d1d1 ("libbpf: Define powerpc syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- 9a6f8da47302 ("libbpf: Define powerpc syscall regs spec in bpf_tracing.h")
Skipping 'c1cc01a2d1d1 ("libbpf: Define powerpc syscall regs spec in bpf_tracing.h")' due to unique match...
Commit '377c15b1a2cd ("libbpf: Define sparc syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- 2c58ba33fb1d ("libbpf: Define sparc syscall regs spec in bpf_tracing.h")
Skipping '377c15b1a2cd ("libbpf: Define sparc syscall regs spec in bpf_tracing.h")' due to unique match...
Commit 'a0426216a320 ("libbpf: Define riscv syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- ed66fb297d78 ("libbpf: Define riscv syscall regs spec in bpf_tracing.h")
Skipping 'a0426216a320 ("libbpf: Define riscv syscall regs spec in bpf_tracing.h")' due to unique match...
Commit '2cf802737fb9 ("libbpf: Define arc syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- ef191974b372 ("libbpf: Define arc syscall regs spec in bpf_tracing.h")
Skipping '2cf802737fb9 ("libbpf: Define arc syscall regs spec in bpf_tracing.h")' due to unique match...
Commit '12a299f0b5c7 ("libbpf: Define loongarch syscall regs spec in bpf_tracing.h")' is synced into libbpf as:
- 97740e51032f ("libbpf: Define loongarch syscall regs spec in bpf_tracing.h")
Skipping '12a299f0b5c7 ("libbpf: Define loongarch syscall regs spec in bpf_tracing.h")' due to unique match...
Commit 'a4d325ae461c ("libbpf: Clean up now not needed __PT_PARM{1-6}_SYSCALL_REG defaults")' is synced into libbpf as:
- 004ed7120bec ("libbpf: Clean up now not needed __PT_PARM{1-6}_SYSCALL_REG defaults")
Skipping 'a4d325ae461c ("libbpf: Clean up now not needed __PT_PARM{1-6}_SYSCALL_REG defaults")' due to unique match...
Commit '913b2255c3d8 ("libbpf: Support sleepable struct_ops.s section")' is synced into libbpf as:
- 112479afb736 ("libbpf: Support sleepable struct_ops.s section")
Skipping '913b2255c3d8 ("libbpf: Support sleepable struct_ops.s section")' due to unique match...
Commit '139df64d26fd ("libbpf: Fix malformed documentation formatting")' is synced into libbpf as:
- LINUX_abcf0d18c29d ("libbpf: Fix malformed documentation formatting")
Skipping '139df64d26fd ("libbpf: Fix malformed documentation formatting")' due to unique match...
Commit 'e4ce876f10a2 ("libbpf: Add documentation to map pinning API functions")' is synced into libbpf as:
- LINUX_2b605b44f98a ("libbpf: Add documentation to map pinning API functions")
Skipping 'e4ce876f10a2 ("libbpf: Add documentation to map pinning API functions")' due to unique match...
Commit '1d3cab43f4c7 ("Documentation: bpf: correct spelling")' is synced into libbpf as:
- LINUX_0fd9eb519873 ("Documentation: bpf: correct spelling")
Skipping '1d3cab43f4c7 ("Documentation: bpf: correct spelling")' due to unique match...
Commit 'e85465e420be ("libbpf: Simplify barrier_var()")' is synced into libbpf as:
- LINUX_d8f8f8343465 ("libbpf: Simplify barrier_var()")
Skipping 'e85465e420be ("libbpf: Simplify barrier_var()")' due to unique match...
Commit '25c76ed42821 ("libbpf: Fix unbounded memory access in bpf_usdt_arg()")' is synced into libbpf as:
- LINUX_81a61e1cc213 ("libbpf: Fix unbounded memory access in bpf_usdt_arg()")
Skipping '25c76ed42821 ("libbpf: Fix unbounded memory access in bpf_usdt_arg()")' due to unique match...
Commit '42fae973c2b1 ("libbpf: Fix BPF_PROBE_READ{_STR}_INTO() on s390x")' is synced into libbpf as:
- LINUX_ff985076018a ("libbpf: Fix BPF_PROBE_READ{_STR}_INTO() on s390x")
Skipping '42fae973c2b1 ("libbpf: Fix BPF_PROBE_READ{_STR}_INTO() on s390x")' due to unique match...
Commit 'e2bd9742989b ("tools/bpf: Use tab instead of white spaces to sync bpf.h")' is synced into libbpf as:
- LINUX_ce20254eeb8b ("tools/bpf: Use tab instead of white spaces to sync bpf.h")
Skipping 'e2bd9742989b ("tools/bpf: Use tab instead of white spaces to sync bpf.h")' due to unique match...
Commit '8f1669319c31 ("libbpf: add the capability to specify netlink proto in libbpf_netlink_send_recv")' is synced into libbpf as:
- LINUX_7aadb075d50a ("libbpf: add the capability to specify netlink proto in libbpf_netlink_send_recv")
Skipping '8f1669319c31 ("libbpf: add the capability to specify netlink proto in libbpf_netlink_send_recv")' due to unique match...
Commit '04d58f1b26a4 ("libbpf: add API to get XDP/XSK supported features")' is synced into libbpf as:
- LINUX_4510d4b0b068 ("libbpf: add API to get XDP/XSK supported features")
Skipping '04d58f1b26a4 ("libbpf: add API to get XDP/XSK supported features")' due to unique match...
Commit '17c9b4e1a7d1 ("bpf: fix typo in header for bpf_perf_prog_read_value")' is synced into libbpf as:
- LINUX_0b828e3c0956 ("bpf: fix typo in header for bpf_perf_prog_read_value")
Skipping '17c9b4e1a7d1 ("bpf: fix typo in header for bpf_perf_prog_read_value")' due to unique match...
Commit 'd1d7730ff875 ("libbpf: Correctly set the kernel code version in Debian kernel.")' is synced into libbpf as:
- LINUX_ca3ccc7aa3d3 ("libbpf: Correctly set the kernel code version in Debian kernel.")
Skipping 'd1d7730ff875 ("libbpf: Correctly set the kernel code version in Debian kernel.")' due to unique match...
Commit '02fc0e73e852 ("libbpf: Always use libbpf_err to return an error in bpf_xdp_query()")' is synced into libbpf as:
- LINUX_1f875ad2c406 ("libbpf: Always use libbpf_err to return an error in bpf_xdp_query()")
Skipping '02fc0e73e852 ("libbpf: Always use libbpf_err to return an error in bpf_xdp_query()")' due to unique match...
Commit 'ab8684b8cecf ("libbpf: Add sample_period to creation options")' is synced into libbpf as:
- LINUX_abd5c13d66e8 ("libbpf: Add sample_period to creation options")
Skipping 'ab8684b8cecf ("libbpf: Add sample_period to creation options")' due to unique match...
Commit '17bcd27a08a2 ("libbpf: Fix alen calculation in libbpf_nla_dump_errormsg()")' is synced into libbpf as:
- LINUX_d27a7f143fd7 ("libbpf: Fix alen calculation in libbpf_nla_dump_errormsg()")
Skipping '17bcd27a08a2 ("libbpf: Fix alen calculation in libbpf_nla_dump_errormsg()")' due to unique match...
Commit '9c395c1b99bd ("bpf: Add basic bpf_rb_{root,node} support")' is synced into libbpf as:
- LINUX_5805c784d2f4 ("bpf: Add basic bpf_rb_{root,node} support")
Skipping '9c395c1b99bd ("bpf: Add basic bpf_rb_{root,node} support")' due to unique match...
Rewrite 5805c784d2f4a4f7870c54d5c833bc79fab8f127 (16/16) (61 seconds passed, remaining 0 predicted)
Ref 'refs/heads/libbpf-squash-tip-2023-02-16T22-23-13.708Z' was rewritten
Ref 'refs/heads/libbpf-squash-base-2023-02-16T22-23-13.708Z' was rewritten
Rewrite 990ea88d95e4a7b016cc25a3cd1ad02c14824b0c (13/16) (2 seconds passed, remaining 0 predicted)
Ref 'refs/heads/libbpf-squash-tip-2023-02-16T22-23-13.708Z' was rewritten
Ref 'refs/heads/libbpf-squash-base-2023-02-16T22-23-13.708Z' was rewritten
warning: unable to rmdir 'buck-out/gen/baseline-sources/baseline-sources': Directory not empty
warning: unable to rmdir 'buck-out/gen/target-sources/target-sources': Directory not empty
/tmp/tmp.nN6WLprpLj/patches/0000-cover-letter.patch
/tmp/tmp.nN6WLprpLj/patches/0001-libbpf-Fix-malformed-documentation-formatting.patch
/tmp/tmp.nN6WLprpLj/patches/0002-libbpf-Add-documentation-to-map-pinning-API-function.patch
/tmp/tmp.nN6WLprpLj/patches/0003-Documentation-bpf-correct-spelling.patch
/tmp/tmp.nN6WLprpLj/patches/0004-libbpf-Simplify-barrier_var.patch
/tmp/tmp.nN6WLprpLj/patches/0005-libbpf-Fix-unbounded-memory-access-in-bpf_usdt_arg.patch
/tmp/tmp.nN6WLprpLj/patches/0006-libbpf-Fix-BPF_PROBE_READ-_STR-_INTO-on-s390x.patch
/tmp/tmp.nN6WLprpLj/patches/0007-tools-bpf-Use-tab-instead-of-white-spaces-to-sync-bp.patch
/tmp/tmp.nN6WLprpLj/patches/0008-libbpf-add-the-capability-to-specify-netlink-proto-i.patch
/tmp/tmp.nN6WLprpLj/patches/0009-libbpf-add-API-to-get-XDP-XSK-supported-features.patch
/tmp/tmp.nN6WLprpLj/patches/0010-bpf-fix-typo-in-header-for-bpf_perf_prog_read_value.patch
/tmp/tmp.nN6WLprpLj/patches/0011-libbpf-Correctly-set-the-kernel-code-version-in-Debi.patch
/tmp/tmp.nN6WLprpLj/patches/0012-libbpf-Always-use-libbpf_err-to-return-an-error-in-b.patch
/tmp/tmp.nN6WLprpLj/patches/0013-libbpf-Add-sample_period-to-creation-options.patch
/tmp/tmp.nN6WLprpLj/patches/0014-libbpf-Fix-alen-calculation-in-libbpf_nla_dump_error.patch
/tmp/tmp.nN6WLprpLj/patches/0015-bpf-Add-basic-bpf_rb_-root-node-support.patch
Switched to a new branch 'libbpf-sync-2023-02-16T22-23-13.708Z'
Applying: libbpf: Fix malformed documentation formatting
Applying: libbpf: Add documentation to map pinning API functions
Applying: Documentation: bpf: correct spelling
Applying: libbpf: Simplify barrier_var()
Applying: libbpf: Fix unbounded memory access in bpf_usdt_arg()
Applying: libbpf: Fix BPF_PROBE_READ{_STR}_INTO() on s390x
Applying: tools/bpf: Use tab instead of white spaces to sync bpf.h
Applying: libbpf: add the capability to specify netlink proto in libbpf_netlink_send_recv
Applying: libbpf: add API to get XDP/XSK supported features
Applying: bpf: fix typo in header for bpf_perf_prog_read_value
Applying: libbpf: Correctly set the kernel code version in Debian kernel.
Applying: libbpf: Always use libbpf_err to return an error in bpf_xdp_query()
Applying: libbpf: Add sample_period to creation options
Applying: libbpf: Fix alen calculation in libbpf_nla_dump_errormsg()
Applying: bpf: Add basic bpf_rb_{root,node} support
Updating files: 100% (79672/79672), done.
Switched to branch 'libbpf-tip-2023-02-16T22-23-13.708Z'
[libbpf-sync-2023-02-16T22-23-13.708Z b4d5b1c51af4] sync: auto-generate latest BPF helpers
 1 file changed, 1 insertion(+), 1 deletion(-)
[libbpf-sync-2023-02-16T22-23-13.708Z 02e762982341] sync: latest libbpf changes from kernel
 2 files changed, 2 insertions(+), 2 deletions(-)
SUCCESS! 15 commits synced.
Verifying Linux's and Github's libbpf state
Switched to a new branch 'libbpf-view-2023-02-16T22-23-13.708Z'
Rewrite 6c20822fada1b8adb77fa450d03a0d449686a4a9 (1/1) (0 seconds passed, remaining 0 predicted)
Ref 'refs/heads/libbpf-view-2023-02-16T22-23-13.708Z' was rewritten
Rewrite 42a688fb7ec26aef79fa5cec28585a66dae72d6e (1/1) (0 seconds passed, remaining 0 predicted)
Ref 'refs/heads/libbpf-view-2023-02-16T22-23-13.708Z' was rewritten
Comparing list of files...
Comparing file contents...
Great! Content is identical!
Cleaning up...
Updating files: 100% (79672/79672), done.
Switched to branch 'bpf-next'
Your branch is up to date with 'bpf-next/master'.
Deleted branch libbpf-baseline-2023-02-16T22-23-13.708Z (was a5f6b9d577eb).
Deleted branch libbpf-tip-2023-02-16T22-23-13.708Z (was 6c20822fada1).
Deleted branch libbpf-bpf-baseline-2023-02-16T22-23-13.708Z (was e8c8fd9b8393).
Deleted branch libbpf-bpf-tip-2023-02-16T22-23-13.708Z (was 6c20822fada1).
Deleted branch libbpf-squash-base-2023-02-16T22-23-13.708Z (was 93b84fa02e76).
Deleted branch libbpf-squash-tip-2023-02-16T22-23-13.708Z (was 85f39aa421dd).
Deleted branch libbpf-view-2023-02-16T22-23-13.708Z (was e18441475823).
DONE.
```

### CODE REVIEW

**Comment by anakryiko** [comment]
@liu-song-6 please reuse the same PR when regenerating sync or just updating it locally. Can you also paste the output of scripts/sync-kernel.sh in PR description?

Also it seems like we need to regenerate checked in vmlinux.h for rb_tree types. I use a pretty minimal kernel config, shared with vmtest.sh and CI to compile vmlinux and dump vmlinux.h from it. Here it is for your convenience: https://gist.github.com/anakryiko/1b1bf8ab3dc9a1b677bedcdab65b8814

**Comment by anakryiko** [comment]
@liu-song-6 we need to remove xdp_info from ci/vmtest/configs/ALLOWLIST-5.5.0, it got some functionality that now depends on newer kernel

can you please put the log into code block, right now it's weirdly formatted. Thanks!

**Comment by liu-song-6** [comment]
So "Kernel 5.5.0 on ubuntu-20.04 + selftests" failed xdp_info. All other configurations are good. Can we just add this test to DENYLIST?

**Comment by anakryiko** [comment]
@liu-song-6 I see you are adding include/uapi/linux/netdev.h, let's copy/paste it *as is* (no simplifications). And we should update the script to keep updating it for future patches. See https://github.com/libbpf/libbpf/blob/master/scripts/sync-kernel.sh#L52 for an example.

**Comment by anakryiko** [comment]
@liu-song-6 also let's keep patch subjects consistently "scoped":

sync: add simplified netdev.h from kernel tree 
ci: remove xdp_info from ALLOWLIST-5.5.0 
ci: regenerate vmlinux.h 

Thanks!

**Comment by liu-song-6** [comment]
> @liu-song-6 I see you are adding include/uapi/linux/netdev.h, let's copy/paste it _as is_ (no simplifications). And we should update the script to keep updating it for future patches. See https://github.com/libbpf/libbpf/blob/master/scripts/sync-kernel.sh#L52 for an example.

I think I read somewhere in the doc etc. that the header should be a simplified version. It is actually easier to keep it as-is. Let me revise this. I will also send a separate PR to update doc.

**Comment by liu-song-6** [comment]
I cannot figure out why it fails on s390. Retry with the same code.

**Comment by anakryiko** [comment]
Note sure why LATEST is running for so long, but previous revisions were green on LATEST, so it's just some fluke.

Thanks a lot for doing this sync, it's not the most straightforward one :) You had to do pretty much all the things: add UAPI header and update script, update allowlist, regenerate vmlinux.h. Great job!

**Pull request merged**
