### PR TITLE
fix resolve_full_path; .so does not necessarily have X permission

### PR DESCRIPTION
**Pull request by gfx**
SSIA. Otherwise `SEC("libc.so.6:...")` does not work. We can avoid this issue by specifying the full path of the executable or shared object instead of its basename, though.

### CODE REVIEW

**Comment by chenhengqi** [comment]
Patch like this should be sent to BPF mailing list.

**Comment by anakryiko** [comment]
@gfx are you planning to submit upstream patch for this?

**Comment by gfx** [comment]
@anakryiko Apologies, but I have no time to do so right now. Hope the project accepts pull-requests via GitHub.

**Comment by chenhengqi** [comment]
I can take this if you don't mind.

**Comment by anakryiko** [comment]
@chenhengqi sure, please do, let's get all such small fixes and improvements into the libbpf 1.0. I'd like to release it officially some time soon. Thanks!

**Comment by chenhengqi** [comment]
OK, will do.

**Comment by chenhengqi** [comment]
Addressed by https://github.com/libbpf/libbpf/pull/546/commits/01a23f1f7200ea0e96719c37bd29f5760573eb93.

**Comment by gfx** [comment]
Thank you, @chenhengqi!

**Pull request closed without merging**
