### PR TITLE
README: add a LGTM badge

### PR DESCRIPTION
**Pull request by mrc0mmand**
Follow-up to https://github.com/libbpf/libbpf/pull/88 (especially https://github.com/libbpf/libbpf/pull/88#issuecomment-547600163, cc @evverx)

The result looks like this:
image

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Also, looks like the LGTM integration is working, according to the "checks" section!

**Comment by anakryiko** [comment]
Grades A, B, C, etc are not that meaningful, IMO, should we try the one with a number of alerts instead?

**Comment by mrc0mmand** [comment]
> Grades A, B, C, etc are not that meaningful, IMO, should we try the one with a number of alerts instead?

No problem, updated:

image

**Comment by evverx** [comment]
I think grades are useful especially when there're a lot of "benign" alerts and alerts produced by custom queries that [LGTM kind of downgrades while rating projects](https://help.semmle.com/lgtm-enterprise/user/help/project-scoring-grading.html). By looking just at numbers, it's hard to tell what's going on. Then again, the grade is always shown at the top so it shouldn't be hard to find anyway.

**Pull request merged**
