### PR TITLE
travis: build on ppc64le as well

### PR DESCRIPTION
**Pull request by mrc0mmand**
As ceff1e0363c92b34742e6e88d9506b1eeee39880 reminded me of a similar issue from https://github.com/libbpf/libbpf/pull/98#issuecomment-553873098, let's keep this PR open so it won't get forgotten.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Actually, ceff1e0 makes this issue even worse :-)

```
In file included from libbpf.c:52:0:
libbpf.c: In function ‘bpf_program__record_reloc’:
libbpf_internal.h:59:22: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Werror=format=]
  libbpf_print(level, "libbpf: " fmt, ##__VA_ARGS__); \
                      ^
libbpf_internal.h:62:27: note: in expansion of macro ‘__pr’
 #define pr_warn(fmt, ...) __pr(LIBBPF_WARN, fmt, ##__VA_ARGS__)
                           ^~~~
libbpf.c:1820:4: note: in expansion of macro ‘pr_warn’
    pr_warn("bad call relo offset: %llu\n", (__u64)sym->st_value);
    ^~~~~~~
libbpf.c:1820:38: note: format string is defined here
    pr_warn("bad call relo offset: %llu\n", (__u64)sym->st_value);
                                   ~~~^
                                   %lu
```

**Comment by mrc0mmand** [comment]
@anakryiko on a somewhat unrelated note - are there any plans to mirror/backport at least some of the unit tests? It's nice that `libbpf` here in Travis CI compiles with ASan/UBSan, but without any tests it's pretty much pointless.

For example, commit 04d8fc50abf08237145a3d9f1589de28e625f6c6 [originally contained](https://lore.kernel.org/bpf/20191114185720.1641606-10-ast@kernel.org/) an actual unit test which got stripped during the *mirroring* process.

**Comment by anakryiko** [comment]
Yeah, seems like we need to fix this differently with casting to (unsigned long long) (through shorter typedef, probably) explicitly. I'll work on a fix.

@mrc0mmand, yes, there is a plan to run kselftests as part of libbpf build, I hope I'll get to doing it this month.

**Comment by anakryiko** [comment]
https://patchwork.ozlabs.org/patch/1208678/ should fix this, once synced to github

**Comment by anakryiko** [comment]
@mrc0mmand, I've synced changes, can you please rebase and re-submit so that we can re-run all the tests?

**Comment by mrc0mmand** [comment]
> @mrc0mmand, I've synced changes, can you please rebase and re-submit so that we can re-run all the tests?

Aaand it's all green, thank you!

**Pull request merged**
