### PR TITLE
provide __PT_PARM6_REG.

### PR DESCRIPTION
**Pull request by liyan-ah**
Add r9d as __PT_PARM6_REG.

### CODE REVIEW

**Comment by liyan-ah** [comment]
I'm working on x86_64 architectures, and need to print 11 function parameters. found that arg6 (count from arg1) are not support by default, and only arg7 after can be got from stack. 
is there anything missed? or any other method to get arg6?
based on my work, I create this pr.

**Comment by liyan-ah** [comment]
also, do we has any recommend method / function to get stack parameters?
found no documents

**Comment by chenhengqi** [comment]
https://github.com/libbpf/libbpf#libbpf-and-general-bpf-usage-questions

**Comment by liyan-ah** [comment]
@chenhengqi 
this confused me. only arg1 to arg5 are supported in the api document.

**Comment by anakryiko** [comment]
@liyan-ah please see https://github.com/libbpf/libbpf-bootstrap/issues/111#issuecomment-1251917107, some architectures support more than 5 arguments in registers, so libbpf should provide macros (and BPF_KPROBE support) for those. Please consider submitting a patch for this.

**Pull request closed without merging**
