### PR TITLE
Libbpf sync 2021-12-14T22:25:46.870Z

### PR DESCRIPTION
**Pull request by anakryiko**

### CODE REVIEW

**Comment by anakryiko** [comment]
@iii-i after latest sync, seems like upstream kernel is failing in test_verifier. See https://github.com/libbpf/libbpf/runs/4537988914?check_suite_focus=true. Not sure what "stack smashing" is. Can you please take a look?

**Comment by iii-i** [comment]
Apparently something has overwritten a security cookie that precedes the return address on stack. I'll run the tests manually and see if I can reproduce this.

**Comment by iii-i** [comment]
It didn't really reproduce for me, however, ASan does see it:

```
=================================================================
==193==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x03ffd67fec84 at pc 0x02aa1dec1fc4 bp 0x03ffd67fe908 sp 0x03ffd67fe900
WRITE of size 4 at 0x03ffd67fec84 thread T0
    #0 0x2aa1dec1fc3 in do_test_fixup linux/tools/testing/selftests/bpf/test_verifier.c:933
    #1 0x2aa1dec2f1b in do_test_single linux/tools/testing/selftests/bpf/test_verifier.c:1092
    #2 0x2aa1dec4c95 in do_test linux/tools/testing/selftests/bpf/test_verifier.c:1352
    #3 0x2aa1dec50d3 in main linux/tools/testing/selftests/bpf/test_verifier.c:1401
    #4 0x3ffb22ab3fd in __libc_start_main csu/libc-start.c:308
    #5 0x2aa1deb349b  (/mnt/linux/tools/testing/selftests/bpf/test_verifier+0x3349b)

Address 0x03ffd67fec84 is located in stack of thread T0 at offset 132 in frame
    #0 0x2aa1dec2cc7 in do_test_single linux/tools/testing/selftests/bpf/test_verifier.c:1073

  This frame has 2 object(s):
    [48, 132) 'map_fds' (line 1079) <== Memory access at offset 132 overflows this variable
    [176, 280) 'opts' (line 1077)
```

**Comment by iii-i** [comment]
https://lore.kernel.org/bpf/20211220140436.1975970-1-iii@linux.ibm.com/

I might be a good idea to run the existing x86_64 kernel-patches CI tests with ASan.

**Comment by anakryiko** [comment]
thanks, @iii-i, for investigating. We are working with @thefallentree on adding ability to pull in bpf tree patches into libbpf CI runs to fix this issue. See https://github.com/kernel-patches/vmtest/pull/52

**Comment by iii-i** [comment]
That's nice!

How do you deal with situations like this during development? I just use bpf-next and accept that I will run into a bug that is already fixed in bpf every once in a while.

**Comment by anakryiko** [comment]
Not sure what you mean by "deal with situations like this"?

BTW, it's been fixed (we are currently applying cherry-picked patch from bpf tree automatically). s390x CI run is green again, yay. Thanks for helping with investigation!

**Pull request merged**
