### PR TITLE
README: add BTF and CO-RE info

### PR DESCRIPTION
**Pull request by anakryiko**
Add list of Linux distributions with kernel BTF built-in.
Give few useful links to BPF CO-RE-related material to help users get started.

### CODE REVIEW

**Comment by anakryiko** [comment]
@borkmann, @netoptimizer, @tohojo FYI

**Comment by anakryiko** [comment]
@brendangregg  as well

**Comment by tohojo** [comment]
Thanks for the heads up! A few comments:

- RHEL 8.2 only has LLVM9
- Ubuntu has LLVM10 from v20.04, and Arch Linux also packages LLVM10.

Opened a bug report for the Arch kernel config here: https://bugs.archlinux.org/task/66877

**Comment by anakryiko** [comment]
My bad about RHEL 8.2 and LLVM, I actually got this info from Tom Stellard, but somehow screw up in README. I'll add Ubuntu to the list for LLVM.

**Pull request merged**
