### PR TITLE
Modify the function name to match the name in the libbpf.map file

### PR DESCRIPTION
**Pull request by lavinyya**
old:
image

new:
image

### CODE REVIEW

**Comment by lavinyya** [comment]
> Please add your Signed-off-by: tag with your full name and valid email (see other commits in this repository). Also please add "libbpf: " prefix to the commit subject and write proper commit message. Thanks.

I've modified this commit based on your response

**Comment by anakryiko** [comment]
Put this into https://github.com/libbpf/libbpf/releases/tag/v0.8.2, thanks.

**Comment by qmonnet** [comment]
@anakryiko v0.8.2 is currently marked as the “latest” release for the repo, is this expected? Although technically the latest in time, I'd expect the marker to point to the highest version, so that v1.4.0 would be featured on the homepage of the repo?

**Comment by vminet** [comment]
@anakryiko I think there is an issue with the 0.8.2 tag.
It points to a v1.4.0 tree (see https://github.com/libbpf/libbpf/blob/v0.8.2/src/Makefile which has major=1, minor=4 and patch=0). This affects the release tarball too.

Note that the libbpf-0.8.2 branch is fine.

**Comment by anakryiko** [comment]
> @anakryiko v0.8.2 is currently marked as the “latest” release for the repo, is this expected? Although technically the latest in time, I'd expect the marker to point to the highest version, so that v1.4.0 would be featured on the homepage of the repo?

fixed, sorry about that, definitely not intended

**Comment by anakryiko** [comment]
@vminet thanks for letting me know (and sorry for late response, I've been out on vacation for last ~2 weeks). Seems like I screwed up v0.8.2 release completely. I'll do v0.8.3 to avoid confusion and will take down v0.8.2.

Sorry for all the troubles, I'll be more careful with patch releases going forward.

**Comment by anakryiko** [comment]
Ok, v0.8.3 (https://github.com/libbpf/libbpf/releases/tag/v0.8.3) is out, not marked as latest, and point to libbpf-0.8.3 branch. Please let me know if it all looks good to you, @vminet, thanks!

**Pull request merged**
